name: TheGreatChow
favicon: null
layout_spectrum: 0.77483
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3125
  lightness: 0.8538697804324329
  saturation: 0.7253915872424841
  rhythmicContrast: 0.24519714177586138
purpose: []
